**arange:** Nota: la arange(1, 10)función devuelve una matriz con números enteros desde 1 (incluido) hasta 10 (no incluido).

In [1]:
import numpy as np


In [2]:
x = np.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


**greater_equal:**  Devuelve el valor de verdad de (x1 >= x2) por elementos.


In [4]:
x = np.greater_equal(10,12)
print(x)

False


**less_equal:** Devuelve el valor de verdad de (x1 <= x2) por elementos.

In [6]:
x = np.less_equal(13,12)
print(x)

False


**extract:**  Devuelve los elementos de un arreglo que cumplen alguna condición. ( condición , arreglo )

Esto es equivalente a . Si condition es booleano es equivalente a .np.compress(ravel(condition), ravel(arr))np.extractarr[condition]

Tenga en cuenta que placehace exactamente lo contrario de extract.

In [10]:
arr = np.arange(12).reshape((3, 4))
print(arr)
condition = np.mod(arr, 3)==0
print(condition)

y = np.extract(condition,arr)

print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ True False False  True]
 [False False  True False]
 [False  True False False]]
[0 3 6 9]


**flipud:** Invierta el orden de los elementos a lo largo del eje 0 (arriba/abajo).

Para una matriz 2-D, esto voltea las entradas en cada columna en la dirección hacia arriba/abajo. Las filas se conservan, pero aparecen en un orden diferente al anterior.

In [12]:
arr = [1,2,3,4,5,6]

x = np.flipud(arr)

print(x)

[6 5 4 3 2 1]


**ones:** Devuelve una nueva matriz de forma y tipo dados, llena de unos.
numpy.ones(shape, dtype=None, order='C', *, like=None) 

In [13]:
x = np.ones(5)

print(x)

[1. 1. 1. 1. 1.]


**real:** Devuelve la parte real del argumento complejo.

In [14]:
d = a = np.array([1+2j, 3+4j, 5+6j])

x = np.real(d)

print(x)

[1. 3. 5.]


**imag:** Devuelve la parte imaginaria del argumento complejo.

In [15]:
d = a = np.array([1+2j, 3+4j, 5+6j])

x = np.imag(d)

print(x)

[2. 4. 6.]


**np.max** es solo un alias para **np.amax.** Esta función solo funciona en una sola matriz de entrada y encuentra el valor del elemento máximo en toda esa matriz (devolviendo un escalar). Alternativamente, toma un axisargumento y encontrará el valor máximo a lo largo de un eje de la matriz de entrada (devolviendo una nueva matriz).

In [21]:
a = np.array([[0, 1, 6],
                  [2, 4, 1]])
x = np.max(a)

print(x)

6


**amin**

In [24]:
a = np.array([[1, 1, 6],
                  [2, 4, 1]])
x = np.min(a)

print(x)

1
